---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: hadoop
  tasks:
        - name: check if installation exists
          stat:
            path: /home/hadoop/hadoop
          register: installation

        - name: Gets tarball
          get_url:
            url="https://downloads.apache.org/hadoop/common/hadoop-3.3.1/hadoop-3.3.1-aarch64.tar.gz"
            dest="/home/hadoop"
          when: installation.stat.exists == False
          register: new_archive

        - name: Unarchive source
          unarchive:
            src="/home/hadoop/hadoop-3.3.1-aarch64.tar.gz"
            dest="/home/hadoop/"
            copy=no
          when: new_archive is changed

        - name: Remove the hadoop.tar
          file: path="/home/hadoop/hadoop-3.3.1-aarch64.tar.gz" state=absent

        - shell: /usr/bin/java -XshowSettings:properties -version 2>&1 | grep java.home | cut -d'=' -f2 | tr -d ' '
          register: java_op

        - set_fact:
            java_home={{ java_op.stdout }}
        - debug:
            var=java_home
        - name: rename the dir
          command: mv /home/hadoop/hadoop-3.3.1 /home/hadoop/hadoop
          when: new_archive is changed

        - name: Ansible create file profile
          copy:
            dest: "/home/hadoop/.profile"
            content: |
                 export PATH=/home/hadoop/hadoop/bin:/home/hadoop/hadoop/sbin:$PATH
                 export JAVA_HOME={{ java_home }}

        - name: Ansible create file bashrc
          copy:
            dest: "/home/hadoop/.bashrc"
            content: |
                 export PATH=/home/hadoop/hadoop/bin:/home/hadoop/hadoop/sbin:$PATH
                 export JAVA_HOME={{ java_home }}

        - name: moving the files config file
          template: src={{item.src}} dest={{item.dest}} 
          with_items:
              - { src: 'templates/hadoop-env.sh', dest: '/home/hadoop/hadoop/etc/hadoop-env.sh' }
              - { src: 'templates/core-site.xml', dest: '/home/hadoop/hadoop/etc/hadoop/core-site.xml' }
              - { src: 'templates/hdfs-site.xml', dest: '/home/hadoop/hadoop/etc/hadoop/hdfs-site.xml' }
              - { src: 'templates/mapred-site.xml', dest: '/home/hadoop/hadoop/etc/hadoop/mapred-site.xml' }
              - { src: 'templates/yarn-site.xml', dest: '/home/hadoop/hadoop/etc/hadoop/yarn-site.xml' }
            #  - { src: 'templates/workers', dest: '/home/hadoop/hadoop/etc/hadoop/workers' }

        - name: permission for hdfs env
          file:
           path: /home/hadoop/hadoop/etc/hadoop-env.sh
           mode:  0755
