---
- hosts: hadoop-master
  become_user: hadoop
  become: yes
  gather_facts: false

  tasks:
  - name: Scan and save host keys
    shell: "ssh-keyscan -t ecdsa {{ item }}"
    register: ssh_keyscan_results
    changed_when: false
    with_items: 
      - hadoop-master
      - hadoop-node-001
      - hadoop-node-002
      - 0.0.0.0


  - name: Add host keys to local known_hosts file
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
    with_items:
      - "{{ ssh_keyscan_results.results }}"

  - name: Install nfs
    yum: pkg=nfs-utils state=present

  - name: Restart start
    service:
      name: nfs-server
      state: started
      state: enable
