---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  
  - name: Install python3
    yum: pkg=python36

  - name: Install pip
    yum: pkg=python36-pip

  - name: Symlink
    file:
      src: "/usr/bin/python3.6"
      dest: "/usr/bin/python"
      state: link
      force: yes
