---
- hosts: all
  become: yes
  tasks:

  - name: Format hdfs
    shell: |
      curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh && sudo bash add-google-cloud-ops-agent-repo.sh --also-install

  - name: make dir
    file:
        path: "/etc/google/auth"
        state: directory

  - name: moving the files
    template: src={{item.src}} dest={{item.dest}}
    with_items:
          - { src: 'templates/temp.json', dest: '/etc/google/auth/application_default_credentials.json' }
          - { src: 'templates/ops-config.yaml', dest: '/etc/google-cloud-ops-agent/config.yaml'}

  - name: permission for hdfs env
    file:
     path: /etc/google/auth/application_default_credentials.json
     group: root
     owner: root
     mode:  0400

#  - name: touching pos file
#    file:
#     path: /var/lib/google-fluentd/pos/hadoop.pos
#     state: touch

  - name: Restart service ops-agent
    service:
     name: google-cloud-ops-agent
     state: restarted
