---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  - name: install git package
    yum: pkg=git state=present

  - name: Enable Root Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin yes"
      state: present
      backup: yes

  - name: Enable Password Auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication yes"
      state: present
      backup: yes

  - name: Enable Root Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^ChallengeResponseAuthentication'
      line: "ChallengeResponseAuthentication yes"
      state: present
      backup: yes
  
  - name: Disableing SELinux state
    ansible.posix.selinux:
      state: disabled

  - name: Update Root users passcode
    user:
      name: root
      update_password: always
      password: "NsdT0W0.h6SWc"

  - name: Reboot
    reboot:

  - name: Set Sysctl
    sysctl:
      name: vm.swappiness
      value: '5'
  - name: Disable THP support (Causes latcency and mem usage issues)
    shell: echo never {{ ">" }} /sys/kernel/mm/transparent_hugepage/enabled

  - name: Disan;e THP
    shell: echo never {{ ">" }} /sys/kernel/mm/transparent_hugepage/defrag

- hosts: hadoop-master
  gather_facts: no
  tasks:

  - name: get cloudera exe
    get_url:
      url: https://archive.cloudera.com/cm7/7.4.4/cloudera-manager-installer.bin
      dest: /home/bhanu_mar2024
      mode: u+x
    
  - name: clone a github Repo.
    git:
      repo: https://bhanuchandras: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@github.com/bhanuchandras/bigdata.git
      dest: /home/bhanu_mar2024/hadoop

- name: Update Python alternatives to Python 3.8
  hosts: hadoop-master
  become: yes
  gather_facts: no

  tasks:
    - name: Install Python 3.8 if not already installed
      command: "dnf install -y python38"
      ignore_errors: yes

    - name: Set Python 3.8 as the default alternative
      alternatives:
        name: python3
        path: /usr/bin/python3.8
        priority: 1

    - name: Create a virtual environment for Python 3.8
      command: /usr/bin/python3.8 -m venv /home/bhanu_mar2024/hadoop

    - name: Activate the virtual environment
      shell: source /home/bhanu_mar2024/hadoop/bin/activate
      args:
        executable: /bin/bash
        chdir: /home/bhanu_mar2024/hadoop


    - name: Install gcloud-bigquery and gcloud-auth packages
      pip:
        name:
          - google-cloud-bigquery
          - google-auth
        executable: /home/bhanu_mar2024/hadoop/bin/pip
